addons:
  apt:
    packages:
      - lynx

language: java
sudo: false

jdk:
  - oraclejdk8

script:
  - ./gradlew --console plain check

after_failure:
  - if [ -f /home/travis/build/Netflix/Hystrix/hystrix-core/build/reports/tests/test/index.html ]; then lynx -dump /home/travis/build/Netflix/Hystrix/hystrix-core/build/reports/tests/test/index.html; fi
